export enum MutationTypes {
  SET_POSTS = 'SET_POSTS',
  DELETE_POST = 'DELETE_POST',
  STORE_USER_DATA = 'STORE_USER_DATA',
  REMOVE_USER_DATA = 'REMOVE_USER_DATA',
  CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE',
}
